# yaml-language-server: $schema=../../../../../../seadas/seada.io/core-schema-ui/generated/json-schema/templates.json

layout: default
components:
  - id: 43d6b928-eb55-408e-b9d2-f108fa70d796
    label: Box
    type: '@seada.io/basic-ui/Box'
    props:
      size:
        default: 6/12
        md: 7/12
      minSize: auto
      maxSize:
        - 96
        - auto
      margin:
        - 4
        - auto
      padding: 4
      aspectRatio: auto
      borderWidth: '1'
      borderRadius: md
      borderColor: gray-200
      borderStyle: solid
      overlayColor: transparent
      overlayOpacity: 100
    providedProps:
      size: w-6/12 md:w-7/12
      minSize: min-w-auto
      maxSize: max-w-96 max-h-auto
      margin: my-4 mx-auto
      padding: p-4
      aspectRatio: aspect-auto
      borderWidth: border-1
      borderRadius: rounded-md
      borderColor: border-gray-200
      borderStyle: border-solid
      backgroundImage: null
      overlayColor: bg-transparent
      overlayOpacity: bg-opacity-100
    children:
      - id: 93cf1edd-7794-4ff3-ad00-b36218d91a29
        label: Text
        type: '@seada.io/basic-ui/Text'
        props:
          hasHtml: false
          text: Login or register
          fontSize: sm
          textAlign: center
          textColor: black
          letterSpacing: wide
          leading: normal
          fontWeight: semibold
          fontStyle: not-italic
          textDecoration: no-underline
          textDecorationColor: black
          size: full
          minSize: auto
          maxSize: auto
          margin:
            - 0
            - '0'
            - 4
            - '0'
          padding: 0
          aspectRatio: auto
          borderWidth: 0
          borderRadius: none
          borderColor: black
          borderStyle: solid
          overlayColor: transparent
          overlayOpacity: 100
        providedProps:
          hasHtml: false
          text: Login or register
          fontSize: text-sm
          textAlign: text-center
          textColor: text-black
          letterSpacing: tracking-wide
          leading: leading-normal
          fontWeight: font-semibold
          fontStyle: not-italic
          textDecoration: no-underline
          textDecorationColor: decoration-black
          size: w-full
          minSize: min-w-auto
          maxSize: max-w-auto
          margin: mt-0 mr-0 mb-4 ml-0
          padding: p-0
          aspectRatio: aspect-auto
          borderWidth: border-0
          borderRadius: rounded-none
          borderColor: border-black
          borderStyle: border-solid
          backgroundImage: null
          overlayColor: bg-transparent
          overlayOpacity: bg-opacity-100
      - id: ce5d52e8-33b9-47f5-922c-035f432252c9
        label: Login Form
        type: '@seada.io/user/LoginForm'
        props:
          size: full
          minSize: auto
          maxSize: auto
          margin:
            - 0
            - auto
          padding: 0
          aspectRatio: auto
          borderWidth: 0
          borderRadius: none
          borderColor: black
          borderStyle: solid
          overlayColor: transparent
          overlayOpacity: 100
          redirect: home
        providedProps:
          redirect: home
          size: w-full
          minSize: min-w-auto
          maxSize: max-w-auto
          margin: my-0 mx-auto
          padding: p-0
          aspectRatio: aspect-auto
          borderWidth: border-0
          borderRadius: rounded-none
          borderColor: border-black
          borderStyle: border-solid
          backgroundImage: null
          overlayColor: bg-transparent
          overlayOpacity: bg-opacity-100
