# yaml-language-server: $schema=../../../../../../seadas/seada.io/core-schema/generated/json-schema/templates.json

layout: default
components:
  - id: 3fb69c30-7a43-41f0-b6aa-3d84167c8fc7
    label: Product Name
    type: '@seada.io/catalog/ProductName'
    props:
      fontSize: base
      textAlign: left
      textColor: gray-900
      letterSpacing: normal
      leading: normal
      fontWeight:
        default: semibold
      fontStyle: not-italic
      textDecoration: no-underline
      textDecorationColor: black
      size: full
      minSize: auto
      maxSize: auto
      margin:
        - '4'
        - '0'
      padding: '0'
      aspectRatio: auto
      borderWidth: '0'
      borderRadius: none
      borderColor: black
      borderStyle: solid
      overlayColor: transparent
      overlayOpacity: 100
  - id: cfc5b372-a9d8-438f-89dc-46fe57c6beac
    label: Flex Layout
    type: '@seada.io/basic-ui/FlexLayout'
    props:
      flexDirection: row
      flexAlign: start
      gap:
        default: '4'
      size: full
      minSize: auto
      maxSize: auto
      margin: '0'
      padding: '0'
      aspectRatio: auto
      borderWidth: '0'
      borderRadius: none
      borderColor: black
      borderStyle: solid
      overlayColor: transparent
      overlayOpacity: 100
      flexJustify: between
    children:
      - id: 0d6efc36-3353-49cd-b3ea-590c7b1eed10
        label: Product Images Gallery
        type: '@seada.io/catalog/ProductGallery'
        props:
          size: 4/12
          minSize: auto
          maxSize: auto
          margin: '0'
          padding: '0'
          aspectRatio: auto
          borderWidth: '0'
          borderRadius: none
          borderColor: black
          borderStyle: solid
          overlayColor: transparent
          overlayOpacity: 100
      - id: be3ccc92-873f-4925-a01f-832262f50a43
        label: Product details
        type: '@seada.io/basic-ui/FlexLayout'
        props:
          flexDirection:
            default: col
          flexAlign: start
          gap: '0'
          size: full
          minSize: auto
          maxSize: auto
          margin: '0'
          padding: '0'
          aspectRatio: auto
          borderWidth: '0'
          borderRadius: none
          borderColor: black
          borderStyle: solid
          overlayColor: transparent
          overlayOpacity: 100
          flexJustify: between
        children:
          - id: bc374593-5443-44ab-ba16-3a860099422b
            label: Product Description
            type: '@seada.io/catalog/ProductDescription'
            props:
              fontSize: xs
              textAlign: left
              textColor: black
              letterSpacing: normal
              leading: normal
              fontWeight: normal
              fontStyle: not-italic
              textDecoration: no-underline
              textDecorationColor: black
              size: full
              minSize: auto
              maxSize: auto
              margin: '0'
              padding: '0'
              aspectRatio: auto
              borderWidth: '0'
              borderRadius: none
              borderColor: black
              borderStyle: solid
              overlayColor: transparent
              overlayOpacity: 100
          - id: 66110961-38eb-4aba-80ec-58833bf2717e
            label: Product Options
            type: '@seada.io/catalog/ProductOptions'
            props:
              size: full
              minSize: auto
              maxSize: auto
              margin:
                default:
                  - '3'
                  - '0'
              padding: '0'
              aspectRatio: auto
              borderWidth: '0'
              borderRadius: none
              borderColor: black
              borderStyle: solid
              overlayColor: transparent
              overlayOpacity: 100
          - id: e0565ed6-b2ed-4a4e-9d11-f982a4fc8cf3
            label: SKU
            type: '@seada.io/basic-ui/Text'
            props:
              hasHtml: true
              text: 'SKU: <strong>${product.sku}</strong>'
              fontSize: xs
              textAlign: right
              textColor: black
              letterSpacing: normal
              leading: normal
              fontWeight: normal
              fontStyle: not-italic
              textDecoration: no-underline
              textDecorationColor: black
              visibility: visible
              size: full
              minSize: auto
              maxSize: auto
              margin:
                - '2'
                - 0
              padding: 0
              aspectRatio: auto
              borderWidth: '0'
              borderRadius: none
              borderColor: black
              borderStyle: solid
              overlayColor: transparent
              overlayOpacity: 100
          - id: f2eb1b36-9b18-4c1d-9586-928fe4fcb915
            label: Add To Cart
            type: '@seada.io/cart/AddToCart'
            props:
              size: full
              minSize: auto
              maxSize: auto
              margin:
                - '2'
                - '0'
              padding: '0'
              aspectRatio: auto
              borderWidth: '0'
              borderRadius: none
              borderColor: black
              borderStyle: solid
              overlayColor: transparent
              overlayOpacity: 100
          - id: e59a9300-f4bb-43a0-839b-1e3723bdf354
            label: Product Price
            type: '@seada.io/catalog/ProductPrice'
            props:
              fontSize:
                default: lg
              textAlign: right
              textColor: red-500
              letterSpacing: normal
              leading: normal
              fontWeight:
                default: semibold
              fontStyle: not-italic
              textDecoration: no-underline
              textDecorationColor: black
              size: full
              minSize: auto
              maxSize: auto
              margin: '0'
              padding: '0'
              aspectRatio: auto
              borderWidth: '0'
              borderRadius: none
              borderColor: black
              borderStyle: solid
              overlayColor: transparent
              overlayOpacity: 100
          - id: dcab9e8a-96f9-45d8-8bb7-4b8528f4e5ff
            label: Reference Price
            type: '@seada.io/catalog/ProductReferencePrice'
            props:
              fontSize: base
              textAlign: right
              textColor: gray-600
              letterSpacing: normal
              leading: normal
              fontWeight: normal
              fontStyle: not-italic
              textDecoration: line-through
              textDecorationColor: black
              size: full
              minSize: auto
              maxSize: auto
              margin: '0'
              padding: '0'
              aspectRatio: auto
              borderWidth: '0'
              borderRadius: none
              borderColor: black
              borderStyle: solid
              overlayColor: transparent
              overlayOpacity: 100
  - id: fa4d9204-50fb-4417-8d64-ab95092825de
    label: Text
    type: '@seada.io/basic-ui/Text'
    props:
      hasHtml: false
      text: Prodotti correlati
      fontSize: lg
      textAlign: left
      textColor: gray-900
      letterSpacing: normal
      leading: normal
      fontWeight: semibold
      fontStyle: not-italic
      textDecoration: no-underline
      textDecorationColor: black
      size: full
      minSize: auto
      maxSize: auto
      margin:
        - '3'
        - '0'
      padding: '3'
      aspectRatio: auto
      borderWidth:
        - '0'
        - '0'
        - '1'
        - '0'
      borderRadius: none
      borderColor: slate-400
      borderStyle: solid
      overlayColor: transparent
      overlayOpacity: 100
  - id: 2bf77268-6208-406d-8b23-56e7d8bbd59f
    label: Related Products Carousel
    type: '@seada.io/catalog/RelatedProductsCarousel'
    props:
      slidesPerView: 4
      spaceBetween: 10
      navigation: false
      pagination: false
      centeredSlides: false
      autoplay: false
      autoplayDelay: 5000
      pauseOnMouseEnter: false
      size: full
      minSize: auto
      maxSize: auto
      margin: '0'
      padding: '3'
      aspectRatio: auto
      borderWidth: '0'
      borderRadius: none
      borderColor: black
      borderStyle: solid
      overlayColor: transparent
      overlayOpacity: 100
  - id: 32629132-b42f-4cb8-86d8-31df33784cea
    label: Category Data Context
    type: '@seada.io/catalog/CategoryDataContext'
    props:
      categoryId: '19'
      categoryKey: '19'
    children:
      - id: d0085413-b3b9-4591-9168-e2954a7948d8
        label: Category Name
        type: '@seada.io/catalog/CategoryName'
        props:
          fontSize: base
          textAlign: left
          textColor: black
          letterSpacing: normal
          leading: normal
          fontWeight: semibold
          fontStyle: not-italic
          textDecoration: no-underline
          textDecorationColor: black
          size: full
          minSize: auto
          maxSize: auto
          margin: 0
          padding: 0
          aspectRatio: auto
          borderWidth: 0
          borderRadius: none
          borderColor: black
          borderStyle: solid
          overlayColor: transparent
          overlayOpacity: 100
          visibility: visible
      - id: 9419b204-15aa-4337-8d5c-5e7229bb7b1f
        label: Products Carousel
        type: '@seada.io/catalog/ProductsCarousel'
        props:
          slidesPerView: 5
          spaceBetween: 10
          navigation: false
          pagination: false
          centeredSlides: false
          autoplay: 0
          autoplayDelay: 5000
          pauseOnMouseEnter: false
          size: full
          minSize: auto
          maxSize: auto
          margin: 0
          padding: 0
          aspectRatio: auto
          borderWidth: 0
          borderRadius: none
          borderColor: black
          borderStyle: solid
          overlayColor: transparent
          overlayOpacity: 100
