# yaml-language-server: $schema=../../../../../../seadas/seada.io/core-schema/generated/json-schema/templates.json

layout: default
components:
  - id: 9dfb6ebf-6191-43c0-8b49-5d6c3112b309
    label: Slider
    type: '@seada.io/basic-ui/Slider'
    props:
      slidesPerView: 1
      spaceBetween: 10
      navigation: true
      pagination: false
      centeredSlides: false
      autoplay: 0
      autoplayDelay: 5000
      pauseOnMouseEnter: false
      size:
        default: full
        md:
          - full
          - auto
      minSize: auto
      maxSize: auto
      margin:
        - '3'
        - '0'
      padding: 0
      aspectRatio:
        default: auto
        md: panoramic
        lg: panoramic
      borderWidth: 0
      borderRadius: none
      borderColor: black
      borderStyle: solid
      overlayColor: transparent
      overlayOpacity: 100
    children:
      - id: b568be6e-7d76-4269-8ded-c096a35ac341
        label: Banner
        type: '@seada.io/basic-ui/Banner'
        props:
          title: Trusted studio headphones
          subtitle: >-
            Unleash the Future of Sound: Experience Freedom with Headless
            Headphones!
          textAlign: center
          verticalAlign: center
          titleColor: white
          subtitleColor: slate-300
          buttonColor: black
          size: full
          minSize: auto
          maxSize: auto
          margin: 0
          padding: 0
          aspectRatio:
            default: panoramic
            md: video
          borderWidth: 0
          borderRadius: none
          borderColor: black
          borderStyle: solid
          overlayColor: gray-800
          overlayOpacity: 100
          backgroundImage: >-
            http://localhost:3001/images///headphones-51a84f41-9ff7-4235-bb59-5b948658b082.png
          buttonLabel: Shop now !
          buttonLink: /shop-all
          visibility: visible
      - id: 7f00ff31-a98f-4806-9176-b0da20d01ec6
        label: Banner
        type: '@seada.io/basic-ui/Banner'
        props:
          title: Your space
          subtitle: Revolutionize Your Workspace
          textAlign: center
          verticalAlign: center
          titleColor: white
          subtitleColor: white
          buttonColor: black
          size: full
          minSize: auto
          maxSize: auto
          margin: 0
          padding: 0
          aspectRatio: panoramic
          borderWidth: 0
          borderRadius: none
          borderColor: black
          borderStyle: solid
          overlayColor: emerald-900
          overlayOpacity: 100
          backgroundImage: >-
            https://eexoyj54wxoksbic.public.blob.vercel-storage.com/public/images/phoenix12879_modern_library_professional_book_bb18bc6d-613c-4715-a8ec-38dc94467ed7-fa0cc7e6-c578-4243-98ed-6948a8dd9925.png
          visibility:
            2xl: visible
  - id: 6e1e1a09-4ae6-42a4-9065-7e433d3d2dfc
    label: Products Carousel
    type: '@seada.io/catalog/ProductsCarousel'
    props:
      slidesPerView:
        default: 5
        sm: 3
        md: 4
        xs: 2
      spaceBetween: 10
      navigation: false
      pagination: false
      centeredSlides: false
      autoplay: false
      autoplayDelay: 5000
      pauseOnMouseEnter: false
      size: full
      minSize: auto
      maxSize: auto
      margin:
        - '6'
        - '0'
        - '0'
        - '0'
      padding: '0'
      aspectRatio: auto
      borderWidth: 0
      borderRadius: none
      borderColor: black
      borderStyle: solid
      overlayColor: transparent
      overlayOpacity: 100
      productKeys:
        - OTL
        - OCG
        - TWB
        - OTS
        - ABS
        - CC3C
        - CLC
        - CGLD
      visibility:
        xs: visible
